# Generated by Django 3.2.7 on 2021-09-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_content_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='your_comment',
        ),
    ]
